### ISSUE TITLE
Feature: CLI tool to send JUnit test reports to Fern

### ISSUE THREAD

**Issue by eolatham** [guidewire-oss/fern-reporter#139]
I would like to be able to send JUnit format test reports to Fern to be analyzed the same way Ginkgo tests can be analyzed.

**Comment by eolatham** [comment]
Based on my initial understanding of the Fern implementation, I think it might make sense to develop a small CLI tool that converts JUnit test reports into the existing Fern JSON format and posts them to the existing Fern reporter `/api/testrun` endpoint (similar to what the [Ginkgo client](https://github.com/guidewire-oss/fern-ginkgo-client/blob/main/pkg/client/ginkgo_fern_reporter.go) does).

**Comment by mbristol580** [comment]
based on conversation with eric we have started this work

**Comment by Monforton** [comment]
Result of said work: https://github.com/Monforton/fern-cli

**Comment by eolatham** [comment]
@Monforton Great work, I wonder if we can get this added to the guidewire-oss org.

**Comment by eolatham** [comment]
The CLI is now being developed within guidewire-oss: https://github.com/guidewire-oss/fern-junit-client

**Comment by eolatham** [comment]
Closing this as [v0.1.0](https://github.com/guidewire-oss/fern-junit-client/releases/tag/v0.1.0) of the CLI has been released
